version: '3.3'
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: foodgram-frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  db:
    image: postgres:13.0-alpine
    container_name: db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env


  backend:
    image: just55py/foodgram-backend:latest
    container_name: foodgram-backend
    restart: unless-stopped
    volumes:
      - static_value:/app/foodgram/static/
      - media_value:/app/foodgram/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - frontend


volumes:
  postgres_data:
  static_value:
  media_value:
  dump_value: